# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 17 Oct 2010 18:33:32 +0200
*               @ALL          1
*               @user         8
