<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: maurits
 * Date: Mon, 18 Oct 2010 11:29:55 +0200
 */

$conf['title'] = 'Sproutcore';
$conf['template'] = 'A_Centered_Perspective';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['A_Centered_Perspective']['left_sidebar_content'] = '';
$conf['tpl']['A_Centered_Perspective']['right_sidebar_content'] = '';

// end auto-generated content
