<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: maurits
 * Date: Tue, 02 Nov 2010 22:32:32 +0100
 */

$conf['title'] = 'Sproutcore';
$conf['template'] = 'A_Centered_Perspective';
$conf['license'] = 'cc-by-sa';
$conf['tocminheads'] = '10';
$conf['maxtoclevel'] = '2';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;
$conf['tpl']['A_Centered_Perspective']['left_sidebar_content'] = '';
$conf['tpl']['A_Centered_Perspective']['right_sidebar_content'] = '';

// end auto-generated content
